### ISSUE TITLE
Instantiation of Deck

### ISSUE THREAD

**Issue by rmn36** [themerrymarlin/CWRUtan#1]
How will we instantiate a Deck with cards? What kinds of Decks are there? If there are types of Decks should Deck be abstract and have implementations?

**Comment by themerrymarlin** [comment]
We should probably redesign that to be abstract and have a dev card deck and resource deck implementation. Dev card decks would be instantiated with a set number of each dev card as defined by the rules, and resource decks would essentially be a bottomless deck of the specified resource type

**Comment by rmn36** [comment]
So do we need a class for each resource card type? like Food Deck, Steel Deck, etc?

**Comment by themerrymarlin** [comment]
We could do that or we could give resource decks a type field. Whichever one is more UML friendly, but my hunch would be multiple abstractions

**Comment by rmn36** [comment]
Yeah I think multiple abstractions makes the most sense.

For the Development card Deck how many of each Development type goes into it? Which CardTypes are Development Cards?

**Comment by themerrymarlin** [comment]
Dev card types are spartan(14), year of plenty(2), monopoly(2), road building(2), and victory point(5). Do you think we should split the enums as well?

**Comment by rmn36** [comment]
Yeah definitely going to split the enum.

**Comment by themerrymarlin** [comment]
Sounds good, I'll update the class diagram later tonight and put it on the drive

**Comment by themerrymarlin** [comment]
Yea deck should probably be abstract, with concrete implementations for
resource decks and dev card decks instantiation would vary with deck type,
dev. Card decks have a set number of each card that's defined in the rule
book or online somewhere, and I think resource decks are essentially
bottomless
